### ISSUE TITLE
Potential new feature: ruff linting

### ISSUE THREAD

**Issue by nilsleh** [alan-turing-institute/deepsensor#109]
### Summary

At the moment only `black` is used as a linter, and I think it could be reasonable to introduce [ruff](https://github.com/astral-sh/ruff) as a linter, since it includes all the "good practice" codebase linters in one and easy to add for github CI, and pre-commit hook since it encompasses everything in one command.

@davidwilby just because we were talking about this

### Basic Example

One can run it manually to check errors or have it format code automatically, like `black` does already.

### Drawbacks

Running `ruff` on the code base now would make a lot of changes to a lot of files.

### Implementation PR

I would be happy to do a PR on that.

**Comment by tom-andersson** [comment]
Thanks @nilsleh. I'm not super opinionated. The main github page only mentions catching and removing unused imports - what other errors can it catch? Generally I'd be a bit hesitant about changing the default linter quite far through a project (and the risk of forgetting to update docs etc).

If you are keen and think the added value is worthwhile, you could just try running ruff and submitting a PR, and we just see what the diff looks like. All the changes would be encapsulated in that PR, so it's not really an issue that many files would be changed.
