### ISSUE TITLE
Documentation Request: Complete Parameter Descriptions in GreedyAlgorithm Class

### ISSUE THREAD

**Issue by DaniJonesOcean** [alan-turing-institute/deepsensor#119]
**Description:**
Hello DeepSensor community,

While working with the `GreedyAlgorithm` class in the `deepsensor.active_learning.algorithms` module, my colleague and I noticed that several [parameter descriptions in the documentation](https://alan-turing-institute.github.io/deepsensor/reference/active_learning/algorithms.html#module-deepsensor.active_learning.algorithms) remain incomplete. Could we politely request that these be filled in with the appropriate descriptions?

The documentation path is: [/reference/active_learning/algorithms.html](https://alan-turing-institute.github.io/deepsensor/reference/active_learning/algorithms.html#module-deepsensor.active_learning.algorithms)

**Incomplete Parameter Descriptions:**

The following parameters are missing descriptions:
- `X_t_mask`
- `N_new_context`
- `X_normalised`
- `model_infill_method`
- `query_infill`
- `proposed_infill`
- `context_set_idx`
- `target_set_idx`
- `progress_bar`
- `min_or_max`
- `task_loader`
- `verbose`

**Example:**
Here is an example of an incomplete part of the documentation:
```
X_t_mask (xarray.Dataset | xarray.DataArray, optional) – [Description of the X_t_mask parameter.], defaults to None.
```
We can probably guess what some of these refer to, but we'd rather get the info directly from the developers, if possible! Thanks very much for considering it.  : )

**Comment by tom-andersson** [comment]
Thanks for the nudge on this @DaniJonesOcean, sorry about the lack of documentation. I should be able to update the this the week after next. In the meantime, to avoid you being blocked, note that the default kwarg values should all be reasonable (i.e. shouldn't need fiddling with), and if possible try to infer what you need from [the active learning documentation page](https://alan-turing-institute.github.io/deepsensor/user-guide/active_learning.html).

**Comment by DaniJonesOcean** [comment]
Thanks, @tom-andersson! We appreciate the help

**Comment by tom-andersson** [comment]
Closed by https://github.com/alan-turing-institute/deepsensor/commit/2cf043a7a6ba215831d6b00e38cec7d211be96db, you can now find the updated API reference here: https://alan-turing-institute.github.io/deepsensor/reference/active_learning/algorithms.html

Hopefully this clarifies ambiguities, but let me know if anything is unclear.
