### ISSUE TITLE
Potential bug: GreedyAlgorithm fails for Oracle-related Acquisition Functions 

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/deepsensor#125]
### Description

The example of [Active Learning](https://alan-turing-institute.github.io/deepsensor/user-guide/active_learning.html#active-learning) works defining a normalised era5 gridded data (`xarray.Dataset`) in `target`.  

```
task_loader = TaskLoader(
    context=[era5_ds, land_mask_ds, lowres_aux_ds],
    target=era5_ds,
)
```

However, if I replace the target for a normalised station data (`pandas.DataFrame`), the GreedyAlgorithm with Oracle-related Acquisition Functions fails with an error related to the shapes.

```
---------------------------------------------------------------------------
InvalidSamplingStrategyError              Traceback (most recent call last)
<ipython-input-23-489fc63a5370> in <cell line: 2>()
      1 acquisition_fn = OracleRMSE(model)
----> 2 X_new_df, acquisition_fn_ds = alg(acquisition_fn, placement_tasks, diff=True)

4 frames
/usr/local/lib/python3.10/dist-packages/deepsensor/data/loader.py in sample_df(self, df, sampling_strat, seed)
    728             # Check that we got all the samples we asked for
    729             if num_matches != X_c.shape[1]:
--> 730                 raise InvalidSamplingStrategyError(
    731                     f"Passed a numpy coordinate array to sample pandas DataFrame, "
    732                     f"but the DataFrame did not contain all the requested samples. "

InvalidSamplingStrategyError: Passed a numpy coordinate array to sample pandas DataFrame, but the DataFrame did not contain all the requested samples. Requested 10094 samples but only got 0.
```

I suggest considering changes in [L48](https://github.com/alan-turing-institute/deepsensor/blob/16b8c04e2b98d4532bcf5a4db4e2779dce068f85/deepsensor/active_learning/algorithms.py#L480) where the `InvalidSamplingStrategyError` might originate. 

If I change 

`target_sampling=self.X_t_arr`

to 

`target_sampling=self.X_t_arr.shape[1]`

The GreedyAlgorithm works. 

### Reproduction steps

Find a MWE [here](https://colab.research.google.com/drive/1Xo7J1GGpgWJSG161Om8rlaBdRfJcpGbI?usp=sharing).

### Version

0.3.8

### Screenshots

N/A

### OS

Linux, Mac

**Comment by tom-andersson** [comment]
Hi, will reply properly next week or the week after, but if you set `target_sampling` to an integer (in this case `self.X_t_arr.shape[1]`), it will sample randomly, rather than at the locations in the pandas dataframe, which is not what you want.

**Comment by acocac** [comment]
thank you - I understand it samples randomly, however the current implementation doesn't work to sample at the locations in the data frame. It only works when the target is a `xarray.Dataset`.

**Comment by tom-andersson** [comment]
Right. Thanks very much for the MWE, it's helpful. I took a quick look but couldn't spot the issue. Will get back to it when I can!
