### ISSUE TITLE
Update name/url of slack workspace

### ISSUE THREAD

**Issue by scotthosking** [alan-turing-institute/deepsensor#96]
### Description

We have changed the name and url of the slack workspace - we need to update references to this Slack in the repo and the Google Forms:
- Name: Turing Environment and Sustainability
- URL: https://turing-e-and-s.slack.com/home

### Reproduction steps

```bash
N/A
```

### Version

N/A

### Screenshots

```bash
N/A
```

### OS

Mac

**Comment by tom-andersson** [comment]
Thanks for raising this @scotthosking! However, when I click the existing DeepSensor Slack channel links in the README and documentation, it appears to redirect correctly to the new URL. And the Google Form just asks for email addresses which @kallewesterling then invites manually to the Slack channel. Do we definitely need to update anything, and if so, what specifically needs to update?

**Comment by tom-andersson** [comment]
Hi @scotthosking, just checking back in on the status of this? Are there any links that actually need updating?
